# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false

# File Options
files:
  include: 'lib/theme/sass/**/*.s+(a|c)ss'
  ignore:
    - 'lib/theme/sass/vendor/**/*.*'

# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  property-sort-order:
    - 1
    -
      order: alphabetical

      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - content
